### ISSUE TITLE
Did you reproduced the results in paper?

### ISSUE THREAD

**Issue by TuringKi** [chamorajg/pytorch_depth_and_motion_planning#2]
Hi @chamorajg, thank's for your pytorch version of original ones, may i ask that did you can reproduce the results in KITTI or waymo dataset?

**Comment by chamorajg** [comment]
I am currently working on training on the KITTI dataset. Once completed, I shall also upload the pretrained models on KITTI dataset. Mostly by the end of the month, I shall try to upload the model.
