### ISSUE TITLE
Usage of second frame and it's depth in Object_motion_net

### ISSUE THREAD

**Issue by Naykira** [chamorajg/pytorch_depth_and_motion_planning#3]
Hello! In [this line](https://github.com/chamorajg/pytorch_depth_and_motion_planning/blob/master/train.py#L72), shouldn't 'motion_features' contain the rgb and predicted depth of second frame as well? So index 0 would be 1 in the mentioned line, correct? Please feel free to correct me in case I've understood it incorrectly

**Comment by chamorajg** [comment]
Thanks for raising the issue. I will modify the index and update it from 0 to 1 inorder to use the second frame as well.

**Comment by Naykira** [comment]
Thanks for the quick response. Another question wrt training; as you are already working with kitti, could you tell me how many epochs (approximately) have you been training before you get good results?

**Comment by chamorajg** [comment]
https://github.com/chamorajg/pytorch_depth_and_motion_planning/blob/master/train.py#L72. I have updated the code here. I am working on KITTI during my free time. Generally, it takes around 100 epochs to get good results.

**Comment by chamorajg** [comment]
I am closing this issue as the bug was fixed. If you find any other bug feel free to open one.
